spring:
  profiles:
    active:
      - dev
---  
spring:
  profiles: dev
  application:
    name: config-client-dev.com
    
---
spring:
  profiles: uat
  application:
    name: config-client-uat.com