#这样直接取不同环境取不到，目前只能在程序中指定
spring:
  profiles:
    active:
      - dev
---
server: 
  port: 3333

spring:
  profiles: dev
  cloud:
    config:
      name: springcloud-config-client-3344
      profile: dev
      label: master
      uri: config-server.com  

---
server: 
  port: 3355
  
spring:
  profiles: uat
  cloud:
    config:
      name: springcloud-config-client-3344
      profile: uat
      label: master
      uri: config-server.com
